shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - cached-factory
  - ts-api-utils

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

allowBuilds:
  esbuild: true
  simple-git-hooks: true
