name: jsr Publish

on:
  push:
    tags:
      - v*

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  publish:
    if: github.repository == 'pengzhanbo/utils'
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - run: npx jsr publish
