name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install
        run: pnpm i

      - name: Test
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
